#!/bin/bash

USAGE_INSERTAFTER_ARGUMENT="-a|--insertafter <PATTERN>"
USAGE_REGEXP_ARGUMENT="-r|--regexp <PATTERN>"
USAGE_LINE_ARGUMENT="-l|--line <LINE>"
USAGE="Usage: $0 \
    [-h|--help] \
    [-v|--verbose] \
    $USAGE_REGEXP_ARGUMENT \
    $USAGE_INSERTAFTER_ARGUMENT \
    $USAGE_LINE_ARGUMENT \
    <file>"

VERBOSE="no"
ARGUMENT_ERROR="no"
while [[ $# -gt 0 ]]; do
    case "$1" in
        -a|--insertafter)
            export INSERTAFTER="$2"
            shift 2
            ;;
        -r|--regexp)
            export REGEXP="$2"
            shift 2
            ;;
        -l|--line)
            export LINE="$2"
            shift 2
            ;;
        -v|--verbose)
            export VERBOSE="yes"
            shift 1
            ;;
        -h|--help)
            echo $USAGE
            break
            ;;
        *)
            if [[ "$1" =~ ^- ]]; then
                echo "Error: Unknown parameter: $1"
                ARGUMENT_ERROR="yes"
            fi
            break
            ;;
    esac
done

if [ -z "$INSERTAFTER$REGEXP" ]; then
    echo "Missing argument: $USAGE_INSERTAFTER_ARGUMENT or $USAGE_REGEXP_ARGUMENT"
    ARGUMENT_ERROR="yes"
fi

if [ -z "$LINE" ]; then
    echo "Missing argument: $USAGE_LINE_ARGUMENT"
    ARGUMENT_ERROR="yes"
fi

if [ "$#" -lt 1 ]; then
    echo "Missing argument: <file>"
    ARGUMENT_ERROR="yes"
fi

if [ "$ARGUMENT_ERROR" == "yes" ]; then
    echo $USAGE
    exit 1;
fi

FILE=$1

SED=sed

LINEINFILE="no"
if ! grep -q -e "^$LINE$" "$FILE"; then
  if [ -n "$REGEXP" ] && grep -q "$REGEXP" "$FILE"; then
    if [ -n "$(tail -c 1 $FILE)" ]; then echo >> $FILE; fi
    TEMP_FILE=$(mktemp -t FILE.XXXX)
    tail -r $FILE | $SED '0,/^.*'"$REGEXP"'.*$/s//'"$LINE"'/' | tail -r > $TEMP_FILE
    mv $TEMP_FILE $FILE
  else 
    if [ -n "$INSERTAFTER" ]; then
      if grep -q -e "$INSERTAFTER" "$FILE"; then
        $SED -i "/$INSERTAFTER/a $LINE" "$FILE"
      else
        if [ -n "$(tail -c 1 $FILE)" ]; then echo >> $FILE; fi
        echo $LINE >>$FILE
      fi
    fi
  fi
else
  echo "Line already exists in file: $LINE"
fi

exit 0
